version: "3.8"
services:

   grafana:
      image: "grafana/grafana:latest"
      ports:
         - "3000:3000"
      environment:
         - GF_SECURITY_ADMIN_USER=admin
         - GF_SECURITY_ADMIN_PASSWORD=password
      networks:
         eazybank:
      depends_on:
         - prometheus
   
   prometheus:
      image: prom/prometheus:latest
      ports:
         - "9090:9090"
      volumes:
         - ./prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
         eazybank:
   
   zipkin:
      image: openzipkin/zipkin
      mem_limit: 700m
      ports:
         - "9411:9411"
      networks:
         eazybank:
      
   configserver:
      image: bugbuster2348/configserver:latest
      mem_limit: 700m
      ports:
         - "8071:8071"
      networks:
         eazybank:
      depends_on:
         - zipkin
      environment:
         SPRING_PROFILES_ACTIVE: prod
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   
   eurekaserver:
      image: bugbuster2348/eurekaserver:latest
      mem_limit: 700m
      ports:
         - "8070:8070"
      networks:
         eazybank:
      depends_on:
         - configserver
      deploy:
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
      environment:
         SPRING_PROFILES_ACTIVE: prod
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
   mysqldbAccount:
      container_name: mysqldbAccount
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: 234868ab
         MYSQL_DATABASE: accountdb
      networks:
         eazybank:

   mysqldbLoans:
      container_name: mysqldbLoans
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: 234868ab
         MYSQL_DATABASE: loansdb
      networks:
         eazybank:

   mysqldbCards:
      container_name: mysqldbCards
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: 234868ab
         MYSQL_DATABASE: cardsdb
      networks:
         eazybank:

   accounts:
      image: bugbuster2348/accounts:latest
      mem_limit: 700m
      ports:
         - "8080:8080"
      depends_on:
         - mysqldbAccount
         - configserver
         - eurekaserver
      networks:
         eazybank:
      deploy:
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
      environment:
         SPRING_PROFILES_ACTIVE: prod
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   cards:
      image: bugbuster2348/cards:latest
      mem_limit: 700m
      ports:
         - "9000:9000"
      depends_on:
         - mysqldbCards
         - configserver
         - eurekaserver
      networks:
         eazybank:
      deploy:
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
      environment:
         SPRING_PROFILES_ACTIVE: prod
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   loans:
      image: bugbuster2348/loans:latest
      mem_limit: 700m
      ports:
         - "8090:8090"
      depends_on:
         - mysqldbLoans
         - configserver
         - eurekaserver
      networks:
         eazybank:
      deploy:
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
      environment:
         SPRING_PROFILES_ACTIVE: prod
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   gatewayserver:
      image: bugbuster2348/gatewayserver:latest
      mem_limit: 700m
      ports:
         - "8072:8072"
      depends_on:
         - configserver
         - eurekaserver
         - cards
         - loans
         - accounts
      networks:
         eazybank:
      deploy:
         restart_policy:
            condition: on-failure
            delay: 45s
            max_attempts: 3
            window: 180s
      environment:
         SPRING_PROFILES_ACTIVE: prod
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   
networks:
   eazybank:
   