apiVersion: apps/v1
kind: Deployment
metadata:
   name: accounts-deployment
   labels:
      app: accounts
spec:
   replicas: 2
   selector:
      matchLabels:
         app: accounts
   template:
      metadata:
         labels:
            app: accounts
      spec:
         containers:
         -  name: accounts
            image: bugbuster2348/accounts:latest
            ports:
            -  containerPort: 8080
            env:
            -  name: SPRING_APPLICATION_NAME
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: ACCOUNTS_APPLICATION_NAME
            -  name: SPRING_PROFILES_ACTIVE
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: SPRING_PROFILES_ACTIVE
            -  name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            -  name: SPRING_CONFIG_IMPORT
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: SPRING_CONFIG_IMPORT

            -  name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

            -  name: DB_HOST
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: host

            -  name: DB_NAME
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: dbName

            -  name: DB_USERNAME
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: dbUserName

            -  name: DB_PASSWORD
               valueFrom:
                  configMapKeyRef:
                     name: eazybank-configmap
                     key: dbPassword
---
apiVersion: v1
kind: Service
metadata:
   name: accounts-service
spec:
   selector:
      app: accounts
   type: LoadBalancer
   ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080